//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLibSet.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeLibSet.Data.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; is not a reference column.
        /// </summary>
        internal static string Common_Err_ColumnIsNotRef {
            get {
                return ResourceManager.GetString("Common_Err_ColumnIsNotRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos; has already had a connection.
        /// </summary>
        internal static string DBx_Err_AlreadyConnected {
            get {
                return ResourceManager.GetString("DBx_Err_AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; has a wrong type. Declaration of type {2} requires column type {3}, while real type is {4}.
        /// </summary>
        internal static string DBx_Err_ColumnTypeDiff {
            get {
                return ResourceManager.GetString("DBx_Err_ColumnTypeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid part #{0} of dotted column name. {1}.
        /// </summary>
        internal static string DBx_Err_DotColumnNamePart {
            get {
                return ResourceManager.GetString("DBx_Err_DotColumnNamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when getting connection string. {0}.
        /// </summary>
        internal static string DBx_Err_GetConnectionString {
            get {
                return ResourceManager.GetString("DBx_Err_GetConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a connection to database &apos;{0}&apos; .
        /// </summary>
        internal static string DBx_Err_HasConnection {
            get {
                return ResourceManager.GetString("DBx_Err_HasConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot start with a digit.
        /// </summary>
        internal static string DBx_Err_NameStartsWithDigit {
            get {
                return ResourceManager.GetString("DBx_Err_NameStartsWithDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name is empty.
        /// </summary>
        internal static string DBx_Err_NoColumnName {
            get {
                return ResourceManager.GetString("DBx_Err_NoColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main connection entry has not been initialized yet.
        /// </summary>
        internal static string DBx_Err_NoMainEntry {
            get {
                return ResourceManager.GetString("DBx_Err_NoMainEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is empty.
        /// </summary>
        internal static string DBx_Err_NoTableName {
            get {
                return ResourceManager.GetString("DBx_Err_NoTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment has been changed for column &apos;{0}&apos; in table &apos;{1}&apos; .
        /// </summary>
        internal static string DBx_Msg_ColumnCommentChanged {
            get {
                return ResourceManager.GetString("DBx_Msg_ColumnCommentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; created in table &apos;{1}&apos;.
        /// </summary>
        internal static string DBx_Msg_ColumnCreated {
            get {
                return ResourceManager.GetString("DBx_Msg_ColumnCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of column &apos;{0}&apos; of table &apos;{1}&apos; has been changed from {2} to {3} chars.
        /// </summary>
        internal static string DBx_Msg_ColumnLengthChanged {
            get {
                return ResourceManager.GetString("DBx_Msg_ColumnLengthChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; should have length of {2} char(s) while real column length is greater: {3} char(s).
        /// </summary>
        internal static string DBx_Msg_ColumnLonger {
            get {
                return ResourceManager.GetString("DBx_Msg_ColumnLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For column &apos;{0}&apos; of table &apos;{1}&apos; the DEFAULT value has been reset.
        /// </summary>
        internal static string DBx_Msg_DefaultReset {
            get {
                return ResourceManager.GetString("DBx_Msg_DefaultReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For column &apos;{0}&apos; of table &apos;{1}&apos; the DEFAULT value has been set &apos;{2}&apos;.
        /// </summary>
        internal static string DBx_Msg_DefaultSet {
            get {
                return ResourceManager.GetString("DBx_Msg_DefaultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All indexes for table &apos;{0}&apos; will be removed because the column &apos;{1}&apos; length changed.
        /// </summary>
        internal static string DBx_Msg_DelAllIndexesByColumnLength {
            get {
                return ResourceManager.GetString("DBx_Msg_DelAllIndexesByColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key &apos;{0}&apos; created for the table &apos;{1}&apos; with column(s) &apos;{2}&apos;.
        /// </summary>
        internal static string DBx_Msg_FKCreated {
            get {
                return ResourceManager.GetString("DBx_Msg_FKCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &apos;{0}&apos; for table &apos;{1}&apos; with columns {2}.
        /// </summary>
        internal static string DBx_Msg_IndexCreated {
            get {
                return ResourceManager.GetString("DBx_Msg_IndexCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess index &apos;{0}&apos; removed from table &apos;{1}&apos;.
        /// </summary>
        internal static string DBx_Msg_IndexRemovedExcess {
            get {
                return ResourceManager.GetString("DBx_Msg_IndexRemovedExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &apos;{0}&apos; removed from table &apos;{1}&apos; because it&apos;s mismatch the table structure.
        /// </summary>
        internal static string DBx_Msg_IndexRemovedWrong {
            get {
                return ResourceManager.GetString("DBx_Msg_IndexRemovedWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For column &apos;{0}&apos; of table &apos;{1}&apos; the &apos;{2}&apos; attribute has been set.
        /// </summary>
        internal static string DBx_Msg_NullChanged {
            get {
                return ResourceManager.GetString("DBx_Msg_NullChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For column &apos;{0}&apos; of table &apos;{1}&apos; the NULL values have been replaced to DEFAULT value.
        /// </summary>
        internal static string DBx_Msg_NullToDefaultValue {
            get {
                return ResourceManager.GetString("DBx_Msg_NullToDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key &apos;{0}&apos; for table &apos;{1}&apos; has been added.
        /// </summary>
        internal static string DBx_Msg_PKAdded {
            get {
                return ResourceManager.GetString("DBx_Msg_PKAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key &apos;{0}&apos; for table &apos;{1}&apos; has been removed because table does not use a primary key.
        /// </summary>
        internal static string DBx_Msg_PKRemovedNoPK {
            get {
                return ResourceManager.GetString("DBx_Msg_PKRemovedNoPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key &apos;{0}&apos; for table &apos;{1}&apos; has been removed bacause it was wrong.
        /// </summary>
        internal static string DBx_Msg_PKRemovedWrong {
            get {
                return ResourceManager.GetString("DBx_Msg_PKRemovedWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment has been changed for table &apos;{0}&apos;.
        /// </summary>
        internal static string DBx_Msg_TableCommentChanged {
            get {
                return ResourceManager.GetString("DBx_Msg_TableCommentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; created.
        /// </summary>
        internal static string DBx_Msg_TableCreated {
            get {
                return ResourceManager.GetString("DBx_Msg_TableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating column &apos;{0}&apos; in table &apos;{1}&apos;.
        /// </summary>
        internal static string DBx_Phase_ColumnCreation {
            get {
                return ResourceManager.GetString("DBx_Phase_ColumnCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; length changing.
        /// </summary>
        internal static string DBx_Phase_ColumnSetLength {
            get {
                return ResourceManager.GetString("DBx_Phase_ColumnSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key &apos;{0}&apos; creation.
        /// </summary>
        internal static string DBx_Phase_FKCreation {
            get {
                return ResourceManager.GetString("DBx_Phase_FKCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key verification.
        /// </summary>
        internal static string DBx_Phase_FKVerification {
            get {
                return ResourceManager.GetString("DBx_Phase_FKVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index creation for table &apos;{0}&apos; and columns {1}.
        /// </summary>
        internal static string DBx_Phase_IndexCreation {
            get {
                return ResourceManager.GetString("DBx_Phase_IndexCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &apos;{0}&apos; removing.
        /// </summary>
        internal static string DBx_Phase_IndexRemoving {
            get {
                return ResourceManager.GetString("DBx_Phase_IndexRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating table &apos;{0}&apos;.
        /// </summary>
        internal static string DBx_Phase_TableCreation {
            get {
                return ResourceManager.GetString("DBx_Phase_TableCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no rights to perform the action.
        /// </summary>
        internal static string DBxAccessException_Err_Message {
            get {
                return ResourceManager.GetString("DBxAccessException_Err_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; is not a reference column because doesn&apos;t contain a dot.
        /// </summary>
        internal static string DBxCache_Arg_RefColumnHasNoDot {
            get {
                return ResourceManager.GetString("DBxCache_Arg_RefColumnHasNoDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no column &apos;{0}&apos; in table &apos;{1}&apos; structure.
        /// </summary>
        internal static string DBxCache_Arg_UnknownColumn {
            get {
                return ResourceManager.GetString("DBxCache_Arg_UnknownColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual value for the key &apos;{0}&apos; has not been returned.
        /// </summary>
        internal static string DBxCache_Err_IndividualValueNotReturned {
            get {
                return ResourceManager.GetString("DBxCache_Err_IndividualValueNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get data from the source.
        /// </summary>
        internal static string DBxCache_Err_Load {
            get {
                return ResourceManager.GetString("DBxCache_Err_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table page for the key &apos;{0}&apos; has not been returned.
        /// </summary>
        internal static string DBxCache_Err_TablePageNotReturned {
            get {
                return ResourceManager.GetString("DBxCache_Err_TablePageNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when DBxCache page loaded.
        /// </summary>
        internal static string DBxCache_ErrTitle_Load {
            get {
                return ResourceManager.GetString("DBxCache_ErrTitle_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cache tracing (DBxCache).
        /// </summary>
        internal static string DBxCache_TraceSwitch_Default {
            get {
                return ResourceManager.GetString("DBxCache_TraceSwitch_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. DBxCache query: {1}.
        /// </summary>
        internal static string DBxCacheLoadException_Error_Nessage {
            get {
                return ResourceManager.GetString("DBxCacheLoadException_Error_Nessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give original Version={0} is greater than last existed buffer version {1}.
        /// </summary>
        internal static string DBxClearCacheBuffer_Arg_VersionTooBig {
            get {
                return ResourceManager.GetString("DBxClearCacheBuffer_Arg_VersionTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data row contains DBNull value in primary key column &apos;{0}&apos;.
        /// </summary>
        internal static string DBxCon_Arg_DataRowNullInPKColumn {
            get {
                return ResourceManager.GetString("DBxCon_Arg_DataRowNullInPKColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable does not have the primary key column &apos;{0}&apos; as defined for the table &apos;{1}&apos; of database &apos;{2}&apos;.
        /// </summary>
        internal static string DBxCon_Arg_DataTableHasNoPKColumn {
            get {
                return ResourceManager.GetString("DBxCon_Arg_DataTableHasNoPKColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable must have only one column.
        /// </summary>
        internal static string DBxCon_Arg_DataTableMustHaveSingleColumn {
            get {
                return ResourceManager.GetString("DBxCon_Arg_DataTableMustHaveSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable with rows to find cannot have primary key column &apos;{0}&apos; of table &apos;{1}&apos;.
        /// </summary>
        internal static string DBxCon_Arg_DataTableWithPKColumn {
            get {
                return ResourceManager.GetString("DBxCon_Arg_DataTableWithPKColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command belongs to another connection.
        /// </summary>
        internal static string DBxCon_Arg_DBCommandDiffConnection {
            get {
                return ResourceManager.GetString("DBxCon_Arg_DBCommandDiffConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record identifier is not given.
        /// </summary>
        internal static string DBxCon_Arg_NoId {
            get {
                return ResourceManager.GetString("DBxCon_Arg_NoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable has only primary key columns ({0}). There is no more column for update.
        /// </summary>
        internal static string DBxCon_Arg_UpdateDataTableWithPKOnly {
            get {
                return ResourceManager.GetString("DBxCon_Arg_UpdateDataTableWithPKOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting all rows without a filter is not supported. Use method DeleteAll().
        /// </summary>
        internal static string DBxCon_Arg_UseDeleteAll {
            get {
                return ResourceManager.GetString("DBxCon_Arg_UseDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginUpdate() for the table &apos;{0}&apos; has not been called.
        /// </summary>
        internal static string DBxCon_Err_EndUpdateForTable {
            get {
                return ResourceManager.GetString("DBxCon_Err_EndUpdateForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has not been started.
        /// </summary>
        internal static string DBxCon_Err_NoTransaction {
            get {
                return ResourceManager.GetString("DBxCon_Err_NoTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous transaction has not been finished yet.
        /// </summary>
        internal static string DBxCon_Err_PrevTransaction {
            get {
                return ResourceManager.GetString("DBxCon_Err_PrevTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column list is empty for table &apos;{0}&apos; when database schema loading.
        /// </summary>
        internal static string DBxCon_Err_SchemaColumnListIsEmpty {
            get {
                return ResourceManager.GetString("DBxCon_Err_SchemaColumnListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; in the database &apos;{1}&apos; has no primary key. Rows cannnot be updated..
        /// </summary>
        internal static string DBxCon_Err_UpdateNoPK {
            get {
                return ResourceManager.GetString("DBxCon_Err_UpdateNoPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction rollback error in database &apos;{0}&apos;.
        /// </summary>
        internal static string DBxCon_ErrTitle_Rollback {
            get {
                return ResourceManager.GetString("DBxCon_ErrTitle_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when SQL query executed.
        /// </summary>
        internal static string DBxCon_ErrTitle_Sql {
            get {
                return ResourceManager.GetString("DBxCon_ErrTitle_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; has type {2} and cannot take values of type {3}.
        /// </summary>
        internal static string DBxDataWriter_Arg_ColumnType {
            get {
                return ResourceManager.GetString("DBxDataWriter_Arg_ColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the mode &apos;{0}&apos; column list must contain at least one column not used for the search in the table &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDataWriter_Arg_OtherColumnRequired {
            get {
                return ResourceManager.GetString("DBxDataWriter_Arg_OtherColumnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole column list cannot contains partial set of search columns ({0}) for the table &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDataWriter_Arg_PartialSearchColumns {
            get {
                return ResourceManager.GetString("DBxDataWriter_Arg_PartialSearchColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the mode &apos;{0}&apos; there must be seaarch column(s) in the table.
        /// </summary>
        internal static string DBxDataWriter_Arg_SearchColumnRequired {
            get {
                return ResourceManager.GetString("DBxDataWriter_Arg_SearchColumnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; does not contain a primary key. Primary key is required for the mode {1}.
        /// </summary>
        internal static string DBxDataWriter_Err_NoPK {
            get {
                return ResourceManager.GetString("DBxDataWriter_Err_NoPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not call in Emulation mode.
        /// </summary>
        internal static string DBxFSqlFormatter_Arg_RefTypeEmulation {
            get {
                return ResourceManager.GetString("DBxFSqlFormatter_Arg_RefTypeEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name &apos;{0}&apos; contains invalid chars.
        /// </summary>
        internal static string DBxManager_Arg_FileNameBadChars {
            get {
                return ResourceManager.GetString("DBxManager_Arg_FileNameBadChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection string with name &apos;{0}&apos; in the settings file. Available connection strings are: {1}.
        /// </summary>
        internal static string DBxManager_Err_NoConnectionString {
            get {
                return ResourceManager.GetString("DBxManager_Err_NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name &apos;{0}&apos; does not contain a text fragment &apos;{1}&apos; to replace.
        /// </summary>
        internal static string DBxManager_Err_ReplaceDBItem {
            get {
                return ResourceManager.GetString("DBxManager_Err_ReplaceDBItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown database provider &apos;{0}&apos; for stored connection string &apos;{1}&apos;.
        /// </summary>
        internal static string DBxManager_Err_UnknownProviderForSettings {
            get {
                return ResourceManager.GetString("DBxManager_Err_UnknownProviderForSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias must be given to use expression of type {0}.
        /// </summary>
        internal static string DBxNameExpression_Arg_AliasRequired {
            get {
                return ResourceManager.GetString("DBxNameExpression_Arg_AliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty column list.
        /// </summary>
        internal static string DBxNameValidator_Arg_ColumnListIsEmpty {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_ColumnListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; in database &apos;{2}&apos; is not a refernce column.
        /// </summary>
        internal static string DBxNameValidator_Arg_ColumnNotRef {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_ColumnNotRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column name &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string DBxNameValidator_Arg_InvalidColumnName {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table name &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string DBxNameValidator_Arg_InvalidTableName {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no declaration for column &apos;{0}&apos; of table &apos;{1}&apos; in database &apos;{2}&apos;.
        /// </summary>
        internal static string DBxNameValidator_Arg_UnknownColumnName {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_UnknownColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no declaration for table &apos;{0}&apos; in database &apos;{1}&apos;.
        /// </summary>
        internal static string DBxNameValidator_Arg_UnknownTableName {
            get {
                return ResourceManager.GetString("DBxNameValidator_Arg_UnknownTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no access permission for column &apos;{0}&apos; of table &apos;{1}&apos;.
        /// </summary>
        internal static string DBxNameValidator_Err_ColumnRead {
            get {
                return ResourceManager.GetString("DBxNameValidator_Err_ColumnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no writing permission for column &apos;{0}&apos; of table &apos;{1}&apos;. There is only a reading access permission.
        /// </summary>
        internal static string DBxNameValidator_Err_ColumnWrite {
            get {
                return ResourceManager.GetString("DBxNameValidator_Err_ColumnWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no access permission for table &apos;{0}&apos;.
        /// </summary>
        internal static string DBxNameValidator_Err_TableRead {
            get {
                return ResourceManager.GetString("DBxNameValidator_Err_TableRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no writing permission for table&apos;{0}&apos;.
        /// </summary>
        internal static string DBxNameValidator_Err_TableWrite {
            get {
                return ResourceManager.GetString("DBxNameValidator_Err_TableWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in table &apos;{0}&apos; with identifier {1} not found.
        /// </summary>
        internal static string DBxRecordNotFoundException_Err_Message {
            get {
                return ResourceManager.GetString("DBxRecordNotFoundException_Err_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong column count in the table: {0}. Expected: {1}.
        /// </summary>
        internal static string DBxSelectFormat_Arg_WrongColumnCount {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Arg_WrongColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated call of method  Format() is not allowed. Instance of FillSelectFormatter can be used only once.
        /// </summary>
        internal static string DBxSelectFormat_Err_FormatAlreadyCalled {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_FormatAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BY list presented without the expression list (SELECT *).
        /// </summary>
        internal static string DBxSelectFormat_Err_GroupByWithoutExpr {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_GroupByWithoutExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVING clause presented without GROUP BY.
        /// </summary>
        internal static string DBxSelectFormat_Err_HavingWithoutGroupBy {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_HavingWithoutGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; contains column &apos;{1}&apos;, but there is no alias for it in the DBxFillSelectInfo.Expressions list.
        /// </summary>
        internal static string DBxSelectFormat_Err_NoAliasForColumn {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_NoAliasForColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no definition for column &apos;{0}&apos; in the DBxSqlBuffer.ColumnStructs list.
        /// </summary>
        internal static string DBxSelectFormat_Err_NoColumnInDBxSqlBuffer {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_NoColumnInDBxSqlBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For sql expression &apos;SELECT * FROM {0}&apos; is not possible to get a column list since user has no rights to access to any of table columns.
        /// </summary>
        internal static string DBxSelectFormat_Err_NoColumnsAccessable {
            get {
                return ResourceManager.GetString("DBxSelectFormat_Err_NoColumnsAccessable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions[{0}] &apos;{1}&apos; contains both an aggregate function and a column reference.
        /// </summary>
        internal static string DBxSelectInfo_Err_ColumnAndAggMixed {
            get {
                return ResourceManager.GetString("DBxSelectInfo_Err_ColumnAndAggMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression list not presented. For operator &apos;SELECT * FROM xxx&apos; with an asterisk, clause GROUP BY cannot be used.
        /// </summary>
        internal static string DBxSelectInfo_Err_GroupByWithoutExpression {
            get {
                return ResourceManager.GetString("DBxSelectInfo_Err_GroupByWithoutExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBy list is already filled. Repeated method call is not allowed..
        /// </summary>
        internal static string DBxSelectInfo_Err_InitGroupByAlreadyCalled {
            get {
                return ResourceManager.GetString("DBxSelectInfo_Err_InitGroupByAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression list is empty.
        /// </summary>
        internal static string DBxSelectInfo_Err_NoExpressions {
            get {
                return ResourceManager.GetString("DBxSelectInfo_Err_NoExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; has a multi-column primary key. Primary key on the single column of type {1} required..
        /// </summary>
        internal static string DBxStructChecker_Err_ComplexPK {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_ComplexPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the numeric column &apos;{0}&apos; defined invalid value range: &apos;{1} : {2}&apos;.
        /// </summary>
        internal static string DBxStructChecker_Err_InvNumRange {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_InvNumRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; has no primary key. Primary key on column of type {1} required..
        /// </summary>
        internal static string DBxStructChecker_Err_NoPK {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_NoPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; has the primary key on column  &apos;{1}&apos; of type {2}. Type {3} required.
        /// </summary>
        internal static string DBxStructChecker_Err_PKWrongType {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_PKWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; reference column &apos;{1}&apos; of type {2} to table &apos;{3}&apos;, but its primary key column &apos;{4}&apos; is of type {5}.
        /// </summary>
        internal static string DBxStructChecker_Err_RefColumnTypeMismatch {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_RefColumnTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; reference column &apos;{1}&apos; to table &apos;{2}&apos;, with multi-column primary key.
        /// </summary>
        internal static string DBxStructChecker_Err_RefToTableComplexPK {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_RefToTableComplexPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; reference column &apos;{1}&apos; to table &apos;{2}&apos; without primary key.
        /// </summary>
        internal static string DBxStructChecker_Err_RefToTableNoPK {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_RefToTableNoPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; reference column &apos;{1}&apos; to unknown table &apos;{2}&apos;.
        /// </summary>
        internal static string DBxStructChecker_Err_RefToUnknownTable {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_RefToUnknownTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the string column &apos;{0}&apos; there is no length givem.
        /// </summary>
        internal static string DBxStructChecker_Err_StringColumnWithoutLen {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_StringColumnWithoutLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; has no columns.
        /// </summary>
        internal static string DBxStructChecker_Err_TableWithoutColumns {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_TableWithoutColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no type defined for the column &apos;{0}&apos;.
        /// </summary>
        internal static string DBxStructChecker_Err_UnknownColumnType {
            get {
                return ResourceManager.GetString("DBxStructChecker_Err_UnknownColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in table &apos;{0}&apos; structure declaration. {1}.
        /// </summary>
        internal static string DBxStructException_Err_Message {
            get {
                return ResourceManager.GetString("DBxStructException_Err_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when transaction rolled back.
        /// </summary>
        internal static string DBxTransactionArray_ErrTitle_Roolback {
            get {
                return ResourceManager.GetString("DBxTransactionArray_ErrTitle_Roolback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string DBxUserPermission_Msg_AccessModeFull {
            get {
                return ResourceManager.GetString("DBxUserPermission_Msg_AccessModeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DBxUserPermission_Msg_AccessModeNone {
            get {
                return ResourceManager.GetString("DBxUserPermission_Msg_AccessModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string DBxUserPermission_Msg_AccessModeReadOnly {
            get {
                return ResourceManager.GetString("DBxUserPermission_Msg_AccessModeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If localized error message is not readable (some characters instead of letters), configure Postgresql server to use english language for message output. In the file postgresql.conf set a line &lt;lc_messages = &apos;en_EN.UTF-8&apos;&gt;.
        /// </summary>
        internal static string Npgsql_Msg_UnreadableMessage {
            get {
                return ResourceManager.GetString("Npgsql_Msg_UnreadableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string does not have parameter &apos;Database&apos;.
        /// </summary>
        internal static string NpgsqlDBx_Arg_NoDatabase {
            get {
                return ResourceManager.GetString("NpgsqlDBx_Arg_NoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the system table &apos;pg_constraint&apos; there is a foreign key constraint for the table &apos;{0}&apos; and column with index {1}. For the pair table+column there is no record in column table. Current constraint will not be analyzed but an error is possible when the constraint will be added again..
        /// </summary>
        internal static string NpgsqlDBx_Msg_ConstraintColumnNotFound {
            get {
                return ResourceManager.GetString("NpgsqlDBx_Msg_ConstraintColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the system table &apos;pg_constraint&apos; there is a foreign key constraint with wrong field &apos;conkey&apos;.
        /// </summary>
        internal static string NpgsqlDBx_Msg_ConstraintWrongConkey {
            get {
                return ResourceManager.GetString("NpgsqlDBx_Msg_ConstraintWrongConkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the index &apos;{0}&apos; there is column with a number {1}, which is not found in table &apos;{2}&apos;.
        /// </summary>
        internal static string NpgsqlDBx_Msg_IndexColumnNotFound {
            get {
                return ResourceManager.GetString("NpgsqlDBx_Msg_IndexColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string has invalid value &apos;DataSource&apos;: &apos;{0}&apos;. FIle must have extension &apos;.mdb&apos;.
        /// </summary>
        internal static string OleDbDBx_Arg_FileExtension {
            get {
                return ResourceManager.GetString("OleDbDBx_Arg_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string has invalid value &apos;DataSource&apos;: &apos;{0}&apos;. Parameter must contain a path to the database file..
        /// </summary>
        internal static string OleDbDBx_Arg_InvalidDataSource {
            get {
                return ResourceManager.GetString("OleDbDBx_Arg_InvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string does not have parameter &apos;DataSource&apos;.
        /// </summary>
        internal static string OleDbDBx_Arg_NoDataSource {
            get {
                return ResourceManager.GetString("OleDbDBx_Arg_NoDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OWNER prefix. {0}.
        /// </summary>
        internal static string OracleDBx_Err_OwnerPrefix {
            get {
                return ResourceManager.GetString("OracleDBx_Err_OwnerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value SqlConnectionStringBuilder.AttachDBFilename=&apos;{0}&apos;. File must have the extension &apos;.mdf&apos;, else work with database is unpossible.
        /// </summary>
        internal static string SqlDBx_Arg_FileExtension {
            get {
                return ResourceManager.GetString("SqlDBx_Arg_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string does not have parameters InitialCatalog nor AttachDBFilename, that define database name.
        /// </summary>
        internal static string SqlDBx_Arg_NoDBName {
            get {
                return ResourceManager.GetString("SqlDBx_Arg_NoDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string does not have parameter &apos;DataSource&apos;.
        /// </summary>
        internal static string SQLiteDBx_Arg_NoDataSource {
            get {
                return ResourceManager.GetString("SQLiteDBx_Arg_NoDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns of type date&apos; and &apos;datetime&apos; cannot accept year less than {0}. SQLite then cannot read such a value.
        /// </summary>
        internal static string SQLiteDBx_Arg_YearOutOfRange {
            get {
                return ResourceManager.GetString("SQLiteDBx_Arg_YearOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when type description &apos;{0}&apos; parsed. {1}.
        /// </summary>
        internal static string SQLiteDBx_Err_SplitColumnType {
            get {
                return ResourceManager.GetString("SQLiteDBx_Err_SplitColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; has been recreated since column format changed.
        /// </summary>
        internal static string SQLiteDBx_Msg_TableRecreatedByColumnFormat {
            get {
                return ResourceManager.GetString("SQLiteDBx_Msg_TableRecreatedByColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; struct changing.
        /// </summary>
        internal static string SQLiteDBx_Phase_TableStructChanging {
            get {
                return ResourceManager.GetString("SQLiteDBx_Phase_TableStructChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tables.
        /// </summary>
        internal static string TablePermission_Name_ObjectText0 {
            get {
                return ResourceManager.GetString("TablePermission_Name_ObjectText0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos;.
        /// </summary>
        internal static string TablePermission_Name_ObjectText1 {
            get {
                return ResourceManager.GetString("TablePermission_Name_ObjectText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables {0}.
        /// </summary>
        internal static string TablePermission_Name_ObjectTextN {
            get {
                return ResourceManager.GetString("TablePermission_Name_ObjectTextN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uknown permission &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownUserPermission_Name_Default {
            get {
                return ResourceManager.GetString("UnknownUserPermission_Name_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission for ClassCode=&apos;{0}&apos; has not been created.
        /// </summary>
        internal static string UserPermission_Err_NotCreated {
            get {
                return ResourceManager.GetString("UserPermission_Err_NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access.
        /// </summary>
        internal static string WholeDBPermission_Name_ObjectText {
            get {
                return ResourceManager.GetString("WholeDBPermission_Name_ObjectText", resourceCulture);
            }
        }
    }
}
