//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLibSet.Data.Docs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeLibSet.Data.Docs.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Allowed_Msg_False {
            get {
                return ResourceManager.GetString("Allowed_Msg_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        internal static string Allowed_Msg_True {
            get {
                return ResourceManager.GetString("Allowed_Msg_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong identifier Id={0} for table &apos;BinData&apos; .
        /// </summary>
        internal static string DBxBinDataHandler_Arg_BinDataId {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Arg_BinDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong identifier Id={0} for table &apos;FileNames&apos;.
        /// </summary>
        internal static string DBxBinDataHandler_Arg_FileNameId {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Arg_FileNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too long.
        /// </summary>
        internal static string DBxBinDataHandler_Arg_FileTooLong {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Arg_FileTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;BinData&apos;, Id={0}. Block reading error. {1}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataBlokReading {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataBlokReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block length mismatch in &apos;BinData&apos; table. For block with Id={0} the stored in database value is {1}, but queried length is {2}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataLength {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no replays found in table &apos;BinData&apos; (&apos;{0}&apos;).
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataNoReplays {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataNoReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay in table &apos;BinData&apos;. For Id={0} and Id={1} there is same MD5 checksum =&apos;{2}&apos;.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataReplayMD5 {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataReplayMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos;, table &apos;BinDataStorage&apos;, Id={1}. In the main table &apos;BinData&apos; for this Id section #{2} is required, but #{3} really used.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataStorageDiffSection {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataStorageDiffSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos;, table &apos;BinDataStorage&apos;. Unhandled error: {1}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataStorageError {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos;, table &apos;BinDataStorage&apos; (section #{1}). Warnings found..
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataStorageHasWarnings {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataStorageHasWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos;, table &apos;BinDataStorage&apos; (section #{1}). No errors.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataStorageNoErrors {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataStorageNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos;, table &apos;BinDataStorage&apos;, Id={1}. There is no such Id in main table &apos;BinData&apos;.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataStorageUnknownId {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataStorageUnknownId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total record count in table &apos;BinData&apos; ({0}): {1}, with errors: {2}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataTotalInfo {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataTotalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;BinData&apos;, Id={0}. Wrong data block length. Expected: {1}, read: {2}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataWrongBlockLength {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataWrongBlockLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;BinData&apos;, Id={0}. Wrong data block MD5-checksum.
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataWrongMD5 {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataWrongMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;BinData&apos;, Id={0}. MD5 is zero. Validation skipped..
        /// </summary>
        internal static string DBxBinDataHandler_Err_BinDataZeroMD5 {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_BinDataZeroMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Id={1}. Wrong reference {2}. Table &apos;{3}&apos; does not contain a record with such identifier..
        /// </summary>
        internal static string DBxBinDataHandler_Err_DocRefUnknown {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_DocRefUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; already contains rows. Import is possible when the table is empty..
        /// </summary>
        internal static string DBxBinDataHandler_Err_ImportToNotEmptyTable {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_ImportToNotEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient entry count ({0}) to fragmented databases. Table &apos;BinData&apos; uses section with numbeк {1}.
        /// </summary>
        internal static string DBxBinDataHandler_Err_InsufficientEntryCount {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_InsufficientEntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no section entries added.
        /// </summary>
        internal static string DBxBinDataHandler_Err_NoSectionEntries {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_NoSectionEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of propertiesUseBinData or UseFiles must be set to true. If application does not store such data, the object DBxBinDataHandler should not be created.
        /// </summary>
        internal static string DBxBinDataHandler_Err_NoUsBinDataUseFiles {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_NoUsBinDataUseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add entries to SectionEntries if UseFragmentation=false.
        /// </summary>
        internal static string DBxBinDataHandler_Err_SectionEntriesWithoutFragmentation {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Err_SectionEntriesWithoutFragmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replays in binary data searching.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_BinDataReplaySearch {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_BinDataReplaySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;BinDataStorage&apos; validation in database &apos;{0}&apos;.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_BinDataStorage {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_BinDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data validation.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_BinDataValidation {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_BinDataValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos; validation.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_DBValidation {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_DBValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document references validation.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_DocRefValidation {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_DocRefValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference searching. {0}.
        /// </summary>
        internal static string DBxBinDataHandler_Phase_RefSearching {
            get {
                return ResourceManager.GetString("DBxBinDataHandler_Phase_RefSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database manager list DBxManager.Managers is empty.
        /// </summary>
        internal static string DBxDocConnectionHelper_Err_DBxManagerListEmpty {
            get {
                return ResourceManager.GetString("DBxDocConnectionHelper_Err_DBxManagerListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct {0} updating. .
        /// </summary>
        internal static string DBxDocConnectionHelper_Err_StructUpdatingPrefix {
            get {
                return ResourceManager.GetString("DBxDocConnectionHelper_Err_StructUpdatingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is not appliable with given settings of DBxDocTypes object.
        /// </summary>
        internal static string DBxDocConnectionHelper_Err_UndoNotAppliable {
            get {
                return ResourceManager.GetString("DBxDocConnectionHelper_Err_UndoNotAppliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderName property has unknown value &apos;{0}&apos;. Available values are: {1}.
        /// </summary>
        internal static string DBxDocConnectionHelper_Err_UnknownProviderName {
            get {
                return ResourceManager.GetString("DBxDocConnectionHelper_Err_UnknownProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocConnectionHelper_Phase_DBUpdating {
            get {
                return ResourceManager.GetString("DBxDocConnectionHelper_Phase_DBUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docProvider cannot be a remote object (transparent proxy) beacause object UserPermissions is not serializable.
        /// </summary>
        internal static string DBxDocPermissions_Arg_DocProviderIsProxy {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Arg_DocProviderIsProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no acccess rights {0} document &apos;{1}&apos; &apos;{2}&apos;. {3}.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDenied {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to delete.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedDelete {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to edit.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedEdit {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to create.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedNew {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to restore.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedRestore {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to view.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedView {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to view history of.
        /// </summary>
        internal static string DBxDocPermissions_Err_AccessDeniedViewHistory {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_AccessDeniedViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to docProvider does not return UserPermissions property.  Context switch is probably appear and UserPermissions object is not serializable. DBxDocProvider with its own permission copy should be used..
        /// </summary>
        internal static string DBxDocPermissions_Err_DocProviderWithoutUserPermissions {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_DocProviderWithoutUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no acccess rights {0} documents. {1}.
        /// </summary>
        internal static string DBxDocPermissions_Err_DocSetAccessDenied {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_DocSetAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no acccess rights {0} to documents of type {1}.
        /// </summary>
        internal static string DBxDocPermissions_Err_DocTypeAccessDenied {
            get {
                return ResourceManager.GetString("DBxDocPermissions_Err_DocTypeAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when table &apos;{0}&apos; queried. Deleting document/subdocuments are &apos;{1}&apos;. Validable reference column is &apos;{2}&apos;. {3}.
        /// </summary>
        internal static string DBxDocPrivider_Err_DelRefColumnInfo {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_DelRefColumnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; there are incomplete columns for a variable-table reference &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocPrivider_Err_IncompleteVTRef {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_IncompleteVTRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are references to table &apos;{0}&apos; for identifiers {1}, which are not in database.
        /// </summary>
        internal static string DBxDocPrivider_Err_RefIdsNotInDB {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_RefIdsNotInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the column &apos;{0}&apos; value of table &apos;{1}&apos; since there is no rights to change value.
        /// </summary>
        internal static string DBxDocPrivider_Err_SetValueDenied {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_SetValueDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for variable-table reference &apos;{1}&apos; there is a fictive table id. Column &apos;{2}&apos;={3}, which match the document type &apos;{4}&apos;. These documents are not allowed for this reference. Allowed document types are: {5}.
        /// </summary>
        internal static string DBxDocPrivider_Err_VTRefDisabledDocType {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_VTRefDisabledDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for variable-table reference &apos;{1}&apos; there is a fictive table id. Column &apos;{2}&apos;={3}.
        /// </summary>
        internal static string DBxDocPrivider_Err_VTRefFictiveTable {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_VTRefFictiveTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for variable-table reference &apos;{1}&apos; there are incomplete identifiers. Column &apos;{2}&apos;={3}, and column &apos;{4}&apos;={5}..
        /// </summary>
        internal static string DBxDocPrivider_Err_VTRefIncompleteIds {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_VTRefIncompleteIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for variable-table reference &apos;{1}&apos; there is a fictive document id. Column &apos;{2}&apos;={3}, which not found in table &apos;{4}&apos;.
        /// </summary>
        internal static string DBxDocPrivider_Err_VTRefUnknownDocId {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_VTRefUnknownDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for variable-table reference &apos;{1}&apos; there is a fictive table id. Column &apos;{2}&apos;={3}, which does not match any document type.
        /// </summary>
        internal static string DBxDocPrivider_Err_VTRefUnknownDocType {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_VTRefUnknownDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the table &apos;{0}&apos; for reference column &apos;{1}&apos; there is a fictive identifier {2}, which has no record in docset.
        /// </summary>
        internal static string DBxDocPrivider_Err_WrongFictiveRefId {
            get {
                return ResourceManager.GetString("DBxDocPrivider_Err_WrongFictiveRefId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user action identifier ActionId={0}.
        /// </summary>
        internal static string DBxDocProvider_Arg_ActionId {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_ActionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-zero subdocument identifier given while table &apos;{0}&apos; is a document.
        /// </summary>
        internal static string DBxDocProvider_Arg_SubDocIdForDoc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_SubDocIdForDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown document type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Arg_UnknownDocType {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_UnknownDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subdocument type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Arg_UnknownSubDocType {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_UnknownSubDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown table &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Arg_UnknownTable {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_UnknownTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId cannot be set since DBxDocTypes.UseUsers=false.
        /// </summary>
        internal static string DBxDocProvider_Arg_UserIdNoUsers {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_UserIdNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong identifier {0}.
        /// </summary>
        internal static string DBxDocProvider_Arg_WrongId {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_WrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong identifier {0} in table &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Arg_WrongIdInTable {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_WrongIdInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data set contains different number of tables: &apos;{0}&apos;. Expected: &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Arg_WrongTableCount {
            get {
                return ResourceManager.GetString("DBxDocProvider_Arg_WrongTableCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For document of type &apos;{0}&apos; with DocId={1} cannot get curret values of user id and time from main document table..
        /// </summary>
        internal static string DBxDocProvider_Err_AddFakeUserAction {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_AddFakeUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete {0} because one of it is referenced by {1}.
        /// </summary>
        internal static string DBxDocProvider_Err_DelMulti {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_DelMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete {0} because it referenced by {1}.
        /// </summary>
        internal static string DBxDocProvider_Err_DelSingle {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_DelSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot created next version for document &apos;{0}&apos; with DocId={1} because it exceed maximum possible value {2}.
        /// </summary>
        internal static string DBxDocProvider_Err_DocActionLimitExceeded {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_DocActionLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; with identifier {1} is already in document set.
        /// </summary>
        internal static string DBxDocProvider_Err_DocInDocSet {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_DocInDocSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load all required rows from document table &apos;{0}&apos;. Queried row count: {1}, given: {2}.
        /// </summary>
        internal static string DBxDocProvider_Err_LoadDocRowCount {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_LoadDocRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBxBinDataHandler object not set.
        /// </summary>
        internal static string DBxDocProvider_Err_NoBinDataHandler {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_NoBinDataHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For document of type &apos;{0}&apos; with DocId={1} vesrion mismatch detected. In main document table it is ({2}), but in table &apos;DocActions&apos; it is ({3}). Version vill be updated in main dicument table.
        /// </summary>
        internal static string DBxDocProvider_Err_VersionMismatch {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_VersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing other users actions is not allowed.
        /// </summary>
        internal static string DBxDocProvider_Err_ViewOtherUsersAction {
            get {
                return ResourceManager.GetString("DBxDocProvider_Err_ViewOtherUsersAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when adding fake record to table &apos;UserActions&apos;.
        /// </summary>
        internal static string DBxDocProvider_ErrTitle_AddFakeUserAction {
            get {
                return ResourceManager.GetString("DBxDocProvider_ErrTitle_AddFakeUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ State auto recover from version {0} ].
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionAutoRecover {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionAutoRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoDelete {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoEdit {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoEmpty {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoInsert {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoMixed {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} docs &apos;{1}&apos; ({2}).
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoMultiDocs {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoMultiDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of doc &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocProvider_Msg_ActionInfoSingleDoc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_ActionInfoSingleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ({1}), {2}.
        /// </summary>
        internal static string DBxDocProvider_Msg_DocSubDocText {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_DocSubDocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documents {0}.
        /// </summary>
        internal static string DBxDocProvider_Msg_MultiDocs {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_MultiDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subdocuments {0} of document {1}.
        /// </summary>
        internal static string DBxDocProvider_Msg_MultiSubDocs {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_MultiSubDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ New ].
        /// </summary>
        internal static string DBxDocProvider_Msg_NewDocSubDoc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_NewDocSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document {0}.
        /// </summary>
        internal static string DBxDocProvider_Msg_SingleDoc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_SingleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subdocument {0} of document {0}.
        /// </summary>
        internal static string DBxDocProvider_Msg_SingleSubDoc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Msg_SingleSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user.
        /// </summary>
        internal static string DBxDocProvider_Name_NoUser {
            get {
                return ResourceManager.GetString("DBxDocProvider_Name_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the single document to search refeneces, cannot be given wihout the docuemnt type.
        /// </summary>
        internal static string DBxDocProvider_NoSingleDocType {
            get {
                return ResourceManager.GetString("DBxDocProvider_NoSingleDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document recalculating &apos;{0}&apos; ({1} doc(s).).
        /// </summary>
        internal static string DBxDocProvider_Phase_DocumentRecalc {
            get {
                return ResourceManager.GetString("DBxDocProvider_Phase_DocumentRecalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data set. In the table &apos;{0}&apos; there is a variable reference column {1} with a table identifier, but column &apos;{2}&apos; with document identifier is missed.
        /// </summary>
        internal static string DBxDocProviderIdReplacer_Err_NoDocIdColumn {
            get {
                return ResourceManager.GetString("DBxDocProviderIdReplacer_Err_NoDocIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data set. In the table &apos;{0}&apos; there is a variable reference column &apos;{1}&apos; with a document identifier, but column &apos;{2}&apos; with a table identifier is missed.
        /// </summary>
        internal static string DBxDocProviderIdReplacer_Err_NoTableIdColumn {
            get {
                return ResourceManager.GetString("DBxDocProviderIdReplacer_Err_NoTableIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While adding row to table &apos;{0}&apos;, column &apos;{1}&apos; contains identifier {2} of referenced table, but there is no document table with such an identifier.
        /// </summary>
        internal static string DBxDocProviderIdReplacer_Err_UnknownTableId {
            get {
                return ResourceManager.GetString("DBxDocProviderIdReplacer_Err_UnknownTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents.
        /// </summary>
        internal static string DBxDocSelection_Msg_Empty {
            get {
                return ResourceManager.GetString("DBxDocSelection_Msg_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBxDocProvider is a remote object (TransparentProxy). To correct work it should be created in the current context. Use object of type DBxChainDocProvider.
        /// </summary>
        internal static string DBxDocSet_Arg_ProviderIsProxy {
            get {
                return ResourceManager.GetString("DBxDocSet_Arg_ProviderIsProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdocument &apos;{0}&apos; with identifier SubDocId={1} has state &apos;{2}&apos;, but document &apos;{3}&apos; with identifier DocId={4}, that own the subdocument, has state &apos;{5}&apos;.
        /// </summary>
        internal static string DBxDocSet_Err_DocSubDocStateMismatch {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_DocSubDocStateMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}. Data row has state &apos;Unchanged&apos; but identifier is fictive..
        /// </summary>
        internal static string DBxDocSet_Err_FicvtiveIdInUnchangedRow {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_FicvtiveIdInUnchangedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data with temporary identifier queried, but thete is no &apos;BinData&apos; table in the data set.
        /// </summary>
        internal static string DBxDocSet_Err_NoBinDataTable {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_NoBinDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdocument &apos;{0}&apos; with identifier SubDocId={1} belongs to doucment &apos;{2}&apos; with identifier DocId={3} that misses in data set.
        /// </summary>
        internal static string DBxDocSet_Err_NoDocForSubDoc {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_NoDocForSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with temporary identifier queried, but thete is no &apos;FileNames&apos; table in the data set.
        /// </summary>
        internal static string DBxDocSet_Err_NoFileNameTable {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_NoFileNameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to document or subdocument &apos;{3}&apos; with Id={4}, which is marked as deleted in database.
        /// </summary>
        internal static string DBxDocSet_Err_RefToDeletedInDB {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToDeletedInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to subdocument &apos;{3}&apos; с Id={4} of document &apos;{5}&apos; with DocId={6}, which is marked as deleted in database.
        /// </summary>
        internal static string DBxDocSet_Err_RefToDocDeletedInDB {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToDocDeletedInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to new document or subdocument RefId={3}, but there is no table &apos;{4}&apos; in the data set..
        /// </summary>
        internal static string DBxDocSet_Err_RefToNewButNoTable {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToNewButNoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to new document or subdocument  RefId={3}, but the row in table &apos;{4}&apos; is marked for deletion.
        /// </summary>
        internal static string DBxDocSet_Err_RefToNewDeleted {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToNewDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to new document or subdocument RefId={3}, but the row is in view mode..
        /// </summary>
        internal static string DBxDocSet_Err_RefToNewInUnchangedRow {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToNewInUnchangedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;.  There is a reference to new document or subdocument  RefId={3}, but there is no row in table&apos;{4}&apos; with such an identifier..
        /// </summary>
        internal static string DBxDocSet_Err_RefToNewUnknown {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToNewUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to document or subdocument &apos;{3}&apos; with invalid Id={4} not exist in database.
        /// </summary>
        internal static string DBxDocSet_Err_RefToNotInDB {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToNotInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Id={1}, column &apos;{2}&apos;. There is a reference to exist document or subdocument  RefId={3}, but the row in table &apos;{4}&apos; is marked for deletion.
        /// </summary>
        internal static string DBxDocSet_Err_RefToOldDeleted {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_RefToOldDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data queried for unknown temporary identifier Id={0}.
        /// </summary>
        internal static string DBxDocSet_Err_UnknownBinDataId {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_UnknownBinDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File queried for unknown temporary identifier Id={0}.
        /// </summary>
        internal static string DBxDocSet_Err_UnknownFileNameId {
            get {
                return ResourceManager.GetString("DBxDocSet_Err_UnknownFileNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocSet_Msg_DocWithType {
            get {
                return ResourceManager.GetString("DBxDocSet_Msg_DocWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} documents of type &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocSet_Msg_MultiDocsOfType {
            get {
                return ResourceManager.GetString("DBxDocSet_Msg_MultiDocsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 document of type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocSet_Msg_SingleDocOfType {
            get {
                return ResourceManager.GetString("DBxDocSet_Msg_SingleDocOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdocument &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocSet_Msg_SubDocWithType {
            get {
                return ResourceManager.GetString("DBxDocSet_Msg_SubDocWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No documents).
        /// </summary>
        internal static string DBxDocsLock_Msg_IsEmpty {
            get {
                return ResourceManager.GetString("DBxDocsLock_Msg_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Document creation).
        /// </summary>
        internal static string DBxDocsLock_Msg_LockAdd {
            get {
                return ResourceManager.GetString("DBxDocsLock_Msg_LockAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the lock &apos;{0}&apos; because it conflicts with the lock &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocsLockException_Err_Default {
            get {
                return ResourceManager.GetString("DBxDocsLockException_Err_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a text representation of the document {0}.
        /// </summary>
        internal static string DBxDocsLockException_Err_DocText {
            get {
                return ResourceManager.GetString("DBxDocsLockException_Err_DocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the lock &apos;{0}&apos; because it conflicts with another lock &apos;{1}&apos; set by same user.
        /// </summary>
        internal static string DBxDocsLockException_Err_SameUser {
            get {
                return ResourceManager.GetString("DBxDocsLockException_Err_SameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; access denied.
        /// </summary>
        internal static string DBxDocStructSource_Err_AccessDenied {
            get {
                return ResourceManager.GetString("DBxDocStructSource_Err_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; is not a reference column.
        /// </summary>
        internal static string DBxDocTextHandlers_Arg_NotRefColumn {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Arg_NotRefColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; has not been added to required list for text representation for table &apos;{1}&apos;. Acceptable columns are{2}.
        /// </summary>
        internal static string DBxDocTextHandlers_Arg_UnknownColumnName {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Arg_UnknownColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents &apos;{0}&apos; does not have any text column. These documents cannot be used as a group tree.
        /// </summary>
        internal static string DBxDocTextHandlers_Err_NoTextForGroupTrese {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Err_NoTextForGroupTrese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. {0}.
        /// </summary>
        internal static string DBxDocTextHandlers_Err_RefTextValue {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Err_RefTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id={0}. Error. {1}.
        /// </summary>
        internal static string DBxDocTextHandlers_Err_TextValue {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Err_TextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableId={0}, DocId={1}. Error. {2}.
        /// </summary>
        internal static string DBxDocTextHandlers_Err_VTTextValue {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Err_VTTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (deleted).
        /// </summary>
        internal static string DBxDocTextHandlers_Msg_Deleted {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (in the deleted document).
        /// </summary>
        internal static string DBxDocTextHandlers_Msg_DocDeleted {
            get {
                return ResourceManager.GetString("DBxDocTextHandlers_Msg_DocDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown document table identifier {0}.
        /// </summary>
        internal static string DBxDocTypes_Arg_UnknownTableId {
            get {
                return ResourceManager.GetString("DBxDocTypes_Arg_UnknownTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown table name &apos;{0}&apos;. It must be a documemt or subdocument name.
        /// </summary>
        internal static string DBxDocTypes_Arg_UnknownTableName {
            get {
                return ResourceManager.GetString("DBxDocTypes_Arg_UnknownTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document table identifier cannot be 0.
        /// </summary>
        internal static string DBxDocTypes_Arg_ZeroTableId {
            get {
                return ResourceManager.GetString("DBxDocTypes_Arg_ZeroTableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in table &apos;DocTables&apos;. Document name &apos;{0}&apos; presented twice..
        /// </summary>
        internal static string DBxDocTypes_Err_DocTableNameTwice {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_DocTableNameTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by an identifier TableId can be performed only after database structure is updated. Property DBxDocType.TableId is unknown before update..
        /// </summary>
        internal static string DBxDocTypes_Err_FindByTableIdBeforeUpdate {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_FindByTableIdBeforeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; structure has an invalid primary key by &apos;{1}&apos; column, but &apos;Id&apos; column required.
        /// </summary>
        internal static string DBxDocTypes_Err_InvaldidPK {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_InvaldidPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; structure does not contain the calculated column &apos;{1}&apos;.
        /// </summary>
        internal static string DBxDocTypes_Err_NoCalcCalumn {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_NoCalcCalumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; of table &apos;{1}&apos; is not a reference column.
        /// </summary>
        internal static string DBxDocTypes_Err_NoRefColumn {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_NoRefColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property UsersTableName references to unknown document table &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocTypes_Err_UnknownUsersDocType {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_UnknownUsersDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For table &apos;{0}&apos; in the VT-reference &apos;{1}&apos; column &apos;{2}&apos; used that already used in another reference.
        /// </summary>
        internal static string DBxDocTypes_Err_VTRefColumnUsed {
            get {
                return ResourceManager.GetString("DBxDocTypes_Err_VTRefColumnUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item of &apos;{0}&apos;.
        /// </summary>
        internal static string DBxDocTypes_Msg_SingularTitleDefault {
            get {
                return ResourceManager.GetString("DBxDocTypes_Msg_SingularTitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; declaration contains a reference column &apos;{1}&apos; definition, which refers to unknown table &apos;{2}&apos;.
        /// </summary>
        internal static string DBxExtRefs_Err_RefToUnknownTable {
            get {
                return ResourceManager.GetString("DBxExtRefs_Err_RefToUnknownTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents &apos;{0}&apos;.
        /// </summary>
        internal static string DBxExtRefs_Name_PluralDoc {
            get {
                return ResourceManager.GetString("DBxExtRefs_Name_PluralDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents &apos;{0}&apos;, subdocuments &apos;{1}&apos;.
        /// </summary>
        internal static string DBxExtRefs_Name_PluralSubDoc {
            get {
                return ResourceManager.GetString("DBxExtRefs_Name_PluralSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos;.
        /// </summary>
        internal static string DBxExtRefs_Name_SingularDoc {
            get {
                return ResourceManager.GetString("DBxExtRefs_Name_SingularDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos;, subdocument &apos;{1}&apos;.
        /// </summary>
        internal static string DBxExtRefs_Name_SingularSubDoc {
            get {
                return ResourceManager.GetString("DBxExtRefs_Name_SingularSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; does not belong to document &apos;{1}&apos;.
        /// </summary>
        internal static string DBxMultiDocs_Arg_UnknownColumn {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Arg_UnknownColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no access rights to documens of type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiDocs_Err_AccessDenied {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot create, modify nor delete documens of type  &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiDocs_Err_AccessReadOnly {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_AccessReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document of type &apos;{0}&apos; with identifier {1} not found.
        /// </summary>
        internal static string DBxMultiDocs_Err_DocNotFound {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_DocNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no open documents of type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiDocs_Err_IsEmpty {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value editing is not allowed.
        /// </summary>
        internal static string DBxMultiDocs_Err_IsReadOnly {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set document &apos;{0}&apos; with DocId={1} to state &apos;{2}&apos; since it&apos;s current state is &apos;{3}&apos;.
        /// </summary>
        internal static string DBxMultiDocs_Err_SetDocState {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_SetDocState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All docuiments of type &apos;{0}&apos; must be in state {1}.
        /// </summary>
        internal static string DBxMultiDocs_Err_StateRequired {
            get {
                return ResourceManager.GetString("DBxMultiDocs_Err_StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table reset is not allowed for the subset.
        /// </summary>
        internal static string DBxMultiSubDoc_Err_ResetTableForSubSet {
            get {
                return ResourceManager.GetString("DBxMultiSubDoc_Err_ResetTableForSubSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row for subdocument with identifier {0} not found.
        /// </summary>
        internal static string DBxMultiSubDoc_Err_RowNotFound {
            get {
                return ResourceManager.GetString("DBxMultiSubDoc_Err_RowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachin child subset was created from another subdocument set.
        /// </summary>
        internal static string DBxMultiSubDocs_Arg_MergeAlienSubSet {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Arg_MergeAlienSubSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to append subdocument of type &apos;{0}&apos; row with SubDocId={1}. The row is in state &apos;{2}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Arg_MergeSubSetRowState {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Arg_MergeSubSetRowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no access rights to subdocumens of type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_AccessDenied {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot create, modify nor delete subdocumens of type  &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_AccessReadOnly {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_AccessReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a subdocument since owner document &apos;{0}&apos; with DocId={1} is in state &apos;{2}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_InsertDocState {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_InsertDocState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot detect the document of type&apos;{0}&apos; which is supposed to be the owner of new subdocument since there are more than one ({1}) document of this type exist in the doc set. Use Insert() method overload with a reference to an owner document.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_InsertMultiDocs {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_InsertMultiDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create subdocument of type &apos;{0}&apos; since there are no documents of type &apos;{1}&apos; in doc set.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_InsertNoDocuments {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_InsertNoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no open subdocuments of type &apos;{0}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_IsEmpty {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set all the subdocuments of type &apos;{0}&apos; to state &apos;{1}&apos; since current state is &apos;{2}&apos;.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_SetAllState {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_SetAllState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All subdocuiments of type &apos;{0}&apos; must be in state {1}.
        /// </summary>
        internal static string DBxMultiSubDocs_Err_StateRequired {
            get {
                return ResourceManager.GetString("DBxMultiSubDocs_Err_StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since binary data used in DocTypes, value of BinDataHandler argument must be given.
        /// </summary>
        internal static string DBxRealDocProviderGlobal_Arg_BinDataHandlerIsNull {
            get {
                return ResourceManager.GetString("DBxRealDocProviderGlobal_Arg_BinDataHandlerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History usage is not possible if property {0}={1}.
        /// </summary>
        internal static string DBxRealDocProviderGlobal_Arg_CannotUseHistory {
            get {
                return ResourceManager.GetString("DBxRealDocProviderGlobal_Arg_CannotUseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property DBxDocTypes.UseSessionId cannot be set if the history is not used.
        /// </summary>
        internal static string DBxRealDocProviderGlobal_Arg_CannotUseSessionId {
            get {
                return ResourceManager.GetString("DBxRealDocProviderGlobal_Arg_CannotUseSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id={0}. Error. {1}.
        /// </summary>
        internal static string DBxRealDocProviderSource_Err_GetTextValue {
            get {
                return ResourceManager.GetString("DBxRealDocProviderSource_Err_GetTextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ No name ].
        /// </summary>
        internal static string DBxRealDocProviderSource_Name_Default {
            get {
                return ResourceManager.GetString("DBxRealDocProviderSource_Name_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing ro database.
        /// </summary>
        internal static string DBxShortDocsLock_Name_Default {
            get {
                return ResourceManager.GetString("DBxShortDocsLock_Name_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a subdocument since it belongs to the docuement {0}. Document should be in state Edit or Insert.
        /// </summary>
        internal static string DBxSingleDoc_Err_DelSubDoc {
            get {
                return ResourceManager.GetString("DBxSingleDoc_Err_DelSubDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdocument of type &apos;{0}&apos; with SubDocId={1} belongs to document of type &apos;{2}&apos; with DocId={3}, but DocId={4} expected.
        /// </summary>
        internal static string DBxSingleSubDocs_Arg_SubDocDiffDoc {
            get {
                return ResourceManager.GetString("DBxSingleSubDocs_Arg_SubDocDiffDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get access to subdocument with index {0} since its data row has been removed from the subdocument table (RowState=Detached).
        /// </summary>
        internal static string DBxSingleSubDocs_Err_RowDetached {
            get {
                return ResourceManager.GetString("DBxSingleSubDocs_Err_RowDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdocument must be in state {0}, but actually it&apos;s in state {1}.
        /// </summary>
        internal static string DBxSubDoc_Arg_WrongState {
            get {
                return ResourceManager.GetString("DBxSubDoc_Arg_WrongState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns &apos;{0}&apos; must not be a reference column.
        /// </summary>
        internal static string DBxVTReference_Arg_ColumnIsRef {
            get {
                return ResourceManager.GetString("DBxVTReference_Arg_ColumnIsRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &apos;{0}&apos; must be integer.
        /// </summary>
        internal static string DBxVTReference_Arg_ColumnNoInt {
            get {
                return ResourceManager.GetString("DBxVTReference_Arg_ColumnNoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; does not contain column &apos;{1}&apos;.
        /// </summary>
        internal static string DBxVTReference_Arg_NoColumn {
            get {
                return ResourceManager.GetString("DBxVTReference_Arg_NoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable attribute must be same.
        /// </summary>
        internal static string DBxVTReference_Arg_NullableDiff {
            get {
                return ResourceManager.GetString("DBxVTReference_Arg_NullableDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one document type must be given.
        /// </summary>
        internal static string DocTypePermission_Arg_NoDocTypes {
            get {
                return ResourceManager.GetString("DocTypePermission_Arg_NoDocTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the documents.
        /// </summary>
        internal static string DocTypePermission_Msg_AllDocTypes {
            get {
                return ResourceManager.GetString("DocTypePermission_Msg_AllDocTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents {0}.
        /// </summary>
        internal static string DocTypePermission_Msg_ObjectText {
            get {
                return ResourceManager.GetString("DocTypePermission_Msg_ObjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type list is not set.
        /// </summary>
        internal static string DocTypePermission_Msg_ObjectTextNoDocTypes {
            get {
                return ResourceManager.GetString("DocTypePermission_Msg_ObjectTextNoDocTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History view for {0}.
        /// </summary>
        internal static string DocTypeViewHistoryPermission_Msg_ObjectText {
            get {
                return ResourceManager.GetString("DocTypeViewHistoryPermission_Msg_ObjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated column re.
        /// </summary>
        internal static string RecalcColumnsPermission_Msg_ObjectText {
            get {
                return ResourceManager.GetString("RecalcColumnsPermission_Msg_ObjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcuated column re-evaluating is not allowed.
        /// </summary>
        internal static string RecalcColumnsPermissionMode_Err_Disabled {
            get {
                return ResourceManager.GetString("RecalcColumnsPermissionMode_Err_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcuated column re-evaluating is not allowed if there are no document identifiers given.
        /// </summary>
        internal static string RecalcColumnsPermissionMode_Err_Selected {
            get {
                return ResourceManager.GetString("RecalcColumnsPermissionMode_Err_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string RecalcColumnsPermissionMode_Msg_All {
            get {
                return ResourceManager.GetString("RecalcColumnsPermissionMode_Msg_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string RecalcColumnsPermissionMode_Msg_Disabled {
            get {
                return ResourceManager.GetString("RecalcColumnsPermissionMode_Msg_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected in data view.
        /// </summary>
        internal static string RecalcColumnsPermissionMode_Msg_Selected {
            get {
                return ResourceManager.GetString("RecalcColumnsPermissionMode_Msg_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong declaration of document type &apos;{0}&apos;. Column &apos;{1}&apos; is not a reference column..
        /// </summary>
        internal static string RefDocCommonFilterSet_Arg_GroupIdColumnIsNotRef {
            get {
                return ResourceManager.GetString("RefDocCommonFilterSet_Arg_GroupIdColumnIsNotRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong declaration of document type &apos;{0}&apos;. There is no column &apos;{1}&apos;.
        /// </summary>
        internal static string RefDocCommonFilterSet_Arg_NoGroupIdColumn {
            get {
                return ResourceManager.GetString("RefDocCommonFilterSet_Arg_NoGroupIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents for master table &apos;{0}&apos; not found.
        /// </summary>
        internal static string RefDocCommonFilterSet_Err_UnknownMasterTable {
            get {
                return ResourceManager.GetString("RefDocCommonFilterSet_Err_UnknownMasterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For document type &apos;{0}&apos; the property TreeParentColumnName. is not set. Then these documents cannot produce a group tree..
        /// </summary>
        internal static string RefGroupDocCommonFilter_Arg_NoTreeParentColumnName {
            get {
                return ResourceManager.GetString("RefGroupDocCommonFilter_Arg_NoTreeParentColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original state.
        /// </summary>
        internal static string UndoAction_Msg_Base {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        internal static string UndoAction_Msg_Delete {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string UndoAction_Msg_Edit {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string UndoAction_Msg_Insert {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string UndoAction_Msg_Redo {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UndoAction_Msg_Undo {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action {0}.
        /// </summary>
        internal static string UndoAction_Msg_Unknown {
            get {
                return ResourceManager.GetString("UndoAction_Msg_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View actions of other users.
        /// </summary>
        internal static string ViewOtherUsersActionPermission_Msg_ObjectText {
            get {
                return ResourceManager.GetString("ViewOtherUsersActionPermission_Msg_ObjectText", resourceCulture);
            }
        }
    }
}
